server:
  port: 8080
  tomcat:
    max-http-post-size: 20MB

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    aggressive-lazy-loading: false
    lazy-loading-enabled: true
    jdbc-type-for-null: null

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/thesis?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 3
      max-wait: 60000
      validation-query: select 1 from dual
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

base_result_url: "E:\\annex\\result\\"
base_task_url: "E:\\annex\\task\\"